In [1]:
import numpy as np
import pandas as pd

# Pandas Series

A series is a one dimentional labeled array capable of holding any data type. The axis lables are collectively called index

In [16]:
labels = ['a', 'b', 'c']
list = [10, 20, 30]
arr = np.array([10,20,30])
dict = {1:10, 2:20, 3:30}

In [21]:
pd.Series(list, index=labels)

a    10
b    20
c    30
dtype: int64

In [23]:
pd.Series(dict)

1    10
2    20
3    30
dtype: int64

# DataFrames
When You combine multiple series together then it's called as Dataframes

Creating DataFrame

In [4]:
data = {
    'Name': ['Mac', 'Kam', 'Sak', 'Bo'],
    'Age': [21, 22, 20, 25],
    'City': ['In', 'In', 'Cam', 'Cam'],
    'Salary': [2000000, 30000, 40000, 50000]
}

df = pd.DataFrame(data)

In [5]:
df

  Name  Age City   Salary
0  Mac   21   In  2000000
1  Kam   22   In    30000
2  Sak   20  Cam    40000
3   Bo   25  Cam    50000

In [6]:
data_list = [
    ['Macc', 20, 'In', 20000000],
    ['Sak', 19, 'Cam', 3000000],
    ['Kam', 22, 'In', 900000],
    ['Bo', 25, 'Cam', 1000000]
]

df2 = pd.DataFrame(data_list)
columns = ["Name", "Age","City", "Salary"]
df2 = pd.DataFrame(data_list, columns=columns)
df2

   Name  Age City    Salary
0  Macc   20   In  20000000
1   Sak   19  Cam   3000000
2   Kam   22   In    900000
3    Bo   25  Cam   1000000

In [7]:
df2

   Name  Age City    Salary
0  Macc   20   In  20000000
1   Sak   19  Cam   3000000
2   Kam   22   In    900000
3    Bo   25  Cam   1000000

Selection and indexing in columns

In [8]:
df2[['City','Name']]

  City  Name
0   In  Macc
1  Cam   Sak
2   In   Kam
3  Cam    Bo

Creating new Column

In [14]:
df2["designation"] = ["doc", "eng", "doc", "eng"]
df2

   Name  Age City    Salary designation
0  Macc   20   In  20000000         doc
1   Sak   19  Cam   3000000         eng
2   Kam   22   In    900000         doc
3    Bo   25  Cam   1000000         eng

Deleting Column

In [ ]:
# df2.drop('designation', axis = 1, inplace=True)

In [17]:
df2

   Name  Age City    Salary
0  Macc   20   In  20000000
1   Sak   19  Cam   3000000
2   Kam   22   In    900000
3    Bo   25  Cam   1000000

Selecting Rows

In [22]:
df2.loc[[0,1]]

   Name  Age City    Salary
0  Macc   20   In  20000000
1   Sak   19  Cam   3000000

In [25]:
df2.iloc[3]

Name           Bo
Age            25
City          Cam
Salary    1000000
Name: 3, dtype: object

Selecting Subset of Rows and Columns

In [33]:
df2.loc[[2,3]][["Name", "Age","Salary"]]

  Name  Age   Salary
2  Kam   22   900000
3   Bo   25  1000000

Conditional Selection

In [35]:
df2[df2["Age"] > 22]

  Name  Age City   Salary
3   Bo   25  Cam  1000000

In [37]:
df2[(df2["Age"] > 20) & (df2["City"] == "In")]

  Name  Age City  Salary
2  Kam   22   In  900000

### Missing Data

Finding Missing data

In [89]:
data = {
    'A' : [1, 2, 3, 4, 5],
    'B' : [np.nan, 2, 3, 4, 5],
    'C' : [1, 2, 3, np.nan, np.nan],
    'D' : [1, np.nan, np.nan, np.nan, 5]
}

df3 = pd.DataFrame(data)

In [71]:
# df3.isna().sum()
# df3.isna().any()
df3

   A    B    C    D
0  1  NaN  1.0  1.0
1  2  2.0  2.0  NaN
2  3  3.0  3.0  NaN
3  4  4.0  NaN  NaN
4  5  5.0  NaN  5.0

Removing Missing Data

In [76]:
df3.dropna()

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [77]:
df3

   A    B    C    D
0  1  NaN  1.0  1.0
1  2  2.0  2.0  NaN
2  3  3.0  3.0  NaN
3  4  4.0  NaN  NaN
4  5  5.0  NaN  5.0

In [85]:
df3.dropna(thresh=4)

Empty DataFrame
Columns: [A, B, C, D]
Index: []

Filling the missing data

In [87]:
df3.fillna(0)

   A    B    C    D
0  1  0.0  1.0  1.0
1  2  2.0  2.0  0.0
2  3  3.0  3.0  0.0
3  4  4.0  0.0  0.0
4  5  5.0  0.0  5.0

In [93]:
values = {'A': 0, 'B': 1, 'C': 2, 'D':3}
df3.fillna(value=values)

   A    B    C    D
0  1  1.0  1.0  1.0
1  2  2.0  2.0  3.0
2  3  3.0  3.0  3.0
3  4  4.0  2.0  3.0
4  5  5.0  2.0  5.0

In [94]:
df3.fillna(df3.mean())

   A    B    C    D
0  1  3.5  1.0  1.0
1  2  2.0  2.0  3.0
2  3  3.0  3.0  3.0
3  4  4.0  2.0  3.0
4  5  5.0  2.0  5.0