In [1]:
import numpy as np
import pandas as pd

# Pandas Series

A series is a one dimentional labeled array capable of holding any data type. The axis lables are collectively called index

In [16]:
labels = ['a', 'b', 'c']
list = [10, 20, 30]
arr = np.array([10,20,30])
dict = {1:10, 2:20, 3:30}

In [21]:
pd.Series(list, index=labels)

a    10
b    20
c    30
dtype: int64

In [23]:
pd.Series(dict)

1    10
2    20
3    30
dtype: int64

# DataFrames
When You combine multiple series together then it's called as Dataframes

Creating DataFrame

In [4]:
data = {
    'Name': ['Mac', 'Kam', 'Sak', 'Bo'],
    'Age': [21, 22, 20, 25],
    'City': ['In', 'In', 'Cam', 'Cam'],
    'Salary': [2000000, 30000, 40000, 50000]
}

df = pd.DataFrame(data)

In [5]:
df

  Name  Age City   Salary
0  Mac   21   In  2000000
1  Kam   22   In    30000
2  Sak   20  Cam    40000
3   Bo   25  Cam    50000

In [6]:
data_list = [
    ['Macc', 20, 'In', 20000000],
    ['Sak', 19, 'Cam', 3000000],
    ['Kam', 22, 'In', 900000],
    ['Bo', 25, 'Cam', 1000000]
]

df2 = pd.DataFrame(data_list)
columns = ["Name", "Age","City", "Salary"]
df2 = pd.DataFrame(data_list, columns=columns)
df2

   Name  Age City    Salary
0  Macc   20   In  20000000
1   Sak   19  Cam   3000000
2   Kam   22   In    900000
3    Bo   25  Cam   1000000

In [7]:
df2

   Name  Age City    Salary
0  Macc   20   In  20000000
1   Sak   19  Cam   3000000
2   Kam   22   In    900000
3    Bo   25  Cam   1000000

Selection and indexing in columns

In [8]:
df2[['City','Name']]

  City  Name
0   In  Macc
1  Cam   Sak
2   In   Kam
3  Cam    Bo

Creating new Column

In [14]:
df2["designation"] = ["doc", "eng", "doc", "eng"]
df2

   Name  Age City    Salary designation
0  Macc   20   In  20000000         doc
1   Sak   19  Cam   3000000         eng
2   Kam   22   In    900000         doc
3    Bo   25  Cam   1000000         eng

Deleting Column

In [ ]:
# df2.drop('designation', axis = 1, inplace=True)

In [17]:
df2

   Name  Age City    Salary
0  Macc   20   In  20000000
1   Sak   19  Cam   3000000
2   Kam   22   In    900000
3    Bo   25  Cam   1000000

Selecting Rows

In [22]:
df2.loc[[0,1]]

   Name  Age City    Salary
0  Macc   20   In  20000000
1   Sak   19  Cam   3000000

In [25]:
df2.iloc[3]

Name           Bo
Age            25
City          Cam
Salary    1000000
Name: 3, dtype: object

Selecting Subset of Rows and Columns

In [33]:
df2.loc[[2,3]][["Name", "Age","Salary"]]

  Name  Age   Salary
2  Kam   22   900000
3   Bo   25  1000000

Conditional Selection

In [35]:
df2[df2["Age"] > 22]

  Name  Age City   Salary
3   Bo   25  Cam  1000000

In [37]:
df2[(df2["Age"] > 20) & (df2["City"] == "In")]

  Name  Age City  Salary
2  Kam   22   In  900000

### Missing Data

Finding Missing data

In [3]:
data = {
    'A' : [1, 2, 3, 4, 5],
    'B' : [np.nan, 2, 3, 4, 5],
    'C' : [1, 2, 3, np.nan, np.nan],
    'D' : [1, np.nan, np.nan, np.nan, 5]
}

df3 = pd.DataFrame(data)

In [4]:
# df3.isna().sum()
# df3.isna().any()
df3

   A    B    C    D
0  1  NaN  1.0  1.0
1  2  2.0  2.0  NaN
2  3  3.0  3.0  NaN
3  4  4.0  NaN  NaN
4  5  5.0  NaN  5.0

Removing Missing Data

In [76]:
df3.dropna()

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [77]:
df3

   A    B    C    D
0  1  NaN  1.0  1.0
1  2  2.0  2.0  NaN
2  3  3.0  3.0  NaN
3  4  4.0  NaN  NaN
4  5  5.0  NaN  5.0

In [85]:
df3.dropna(thresh=4)

Empty DataFrame
Columns: [A, B, C, D]
Index: []

Filling the missing data

In [87]:
df3.fillna(0)

   A    B    C    D
0  1  0.0  1.0  1.0
1  2  2.0  2.0  0.0
2  3  3.0  3.0  0.0
3  4  4.0  0.0  0.0
4  5  5.0  0.0  5.0

In [93]:
values = {'A': 0, 'B': 1, 'C': 2, 'D':3}
df3.fillna(value=values)

   A    B    C    D
0  1  1.0  1.0  1.0
1  2  2.0  2.0  3.0
2  3  3.0  3.0  3.0
3  4  4.0  2.0  3.0
4  5  5.0  2.0  5.0

In [5]:
df3.fillna(df3.mean())

   A    B    C    D
0  1  3.5  1.0  1.0
1  2  2.0  2.0  3.0
2  3  3.0  3.0  3.0
3  4  4.0  2.0  3.0
4  5  5.0  2.0  5.0

### Merging Joining Concatination

In [12]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4],
    'Name': ['Mac', 'Kam', 'Sak', 'Bo'],
    'department': ['HR', 'IT', 'HR', 'IT']
})

# Salary information 
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'Salary': [50000, 60000, 55000, 65000, 90000],
    'bonus': [5000, 6000, 5500, 6500, 4000]
})

In [9]:
employees

   employee_id Name department
0            1  Mac         HR
1            2  Kam         IT
2            3  Sak         HR
3            4   Bo         IT

In [14]:
salaries

   employee_id  Salary  bonus
0            1   50000   5000
1            2   60000   6000
2            3   55000   5500
3            6   65000   6500
4            7   90000   4000

In [18]:
pd.merge(employees, salaries, on='employee_id', how='inner')

   employee_id Name department  Salary  bonus
0            1  Mac         HR   50000   5000
1            2  Kam         IT   60000   6000
2            3  Sak         HR   55000   5500

In [20]:
pd.merge(employees, salaries, on='employee_id', how='outer')

   employee_id Name department   Salary   bonus
0            1  Mac         HR  50000.0  5000.0
1            2  Kam         IT  60000.0  6000.0
2            3  Sak         HR  55000.0  5500.0
3            4   Bo         IT      NaN     NaN
4            6  NaN        NaN  65000.0  6500.0
5            7  NaN        NaN  90000.0  4000.0

In [22]:
pd.merge(employees, salaries, on='employee_id', how='left')

   employee_id Name department   Salary   bonus
0            1  Mac         HR  50000.0  5000.0
1            2  Kam         IT  60000.0  6000.0
2            3  Sak         HR  55000.0  5500.0
3            4   Bo         IT      NaN     NaN

In [24]:
pd.merge(employees, salaries, on='employee_id', how='right')

   employee_id Name department  Salary  bonus
0            1  Mac         HR   50000   5000
1            2  Kam         IT   60000   6000
2            3  Sak         HR   55000   5500
3            6  NaN        NaN   65000   6500
4            7  NaN        NaN   90000   4000

Concatination

In [ ]:
conc1 = pd.DataFrame ({
    'A' : ['A0', 'A1', 'A2'],
    'B' : ['B0', 'B1', 'B2'],
    'C' : ['C0', 'C1', 'C2'],
})

conc2 = pd.DataFrame ({
    'A' : ['A4', 'A5', 'A6'],
    'B' : ['B4', 'B5', 'B6'],
    'C' : ['C4', 'C5', 'C6'],
    # 'D' : ['D4', 'D5', 'D6']
})

In [28]:
conc1

    A   B   C
0  A4  B4  C4
1  A5  B5  C5
2  A6  B6  C6

In [32]:
conc2

    A   B   C
0  A4  B4  C4
1  A5  B5  C5
2  A6  B6  C6

In [37]:
pd.concat([conc1, conc2])

    A   B   C    D
0  A0  B0  C0  NaN
1  A1  B1  C1  NaN
2  A2  B2  C2  NaN
0  A4  B4  C4   D4
1  A5  B5  C5   D5
2  A6  B6  C6   D6

In [39]:
pd.concat([conc1, conc2], axis=1)

    A   B   C   A   B   C   D
0  A0  B0  C0  A4  B4  C4  D4
1  A1  B1  C1  A5  B5  C5  D5
2  A2  B2  C2  A6  B6  C6  D6

Joining of 2 DataFrames

In [43]:
join1 = pd.DataFrame({
    'name': ['Mac', 'Bo', 'Kam', 'Tes']
}, index = [1,2,3,4])

join2 = pd.DataFrame({
    'score': [55,66,77,88]
}, index=[2,3,4,5])

In [45]:
join1

  name
1  Mac
2   Bo
3  Kam
4  Tes

In [48]:
join2

   score
2     55
3     66
4     77
5     88

In [50]:
join1.join(join2, how='outer')

  name  score
1  Mac    NaN
2   Bo   55.0
3  Kam   66.0
4  Tes   77.0
5  NaN   88.0

In [3]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}

df = pd.DataFrame(data)
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [18]:
# Group by category and calculate the sum of sales

cat = df.groupby('Category')['Sales'].sum()
cat

Category
A    570
B    930
Name: Sales, dtype: int64

In [20]:
# Group by store and sum of sales
store = df.groupby('Store')['Sales'].sum()
store

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [5]:
# Group by multiple columns 
# Group by category and store

cat = df.groupby(['Category', 'Store'])['Sales'].sum()
cat

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

In [16]:
# Aggregation 
# df['Sales'].mean()
# df['Sales'].median()
# df['Sales'].mode()
# df['Sales'].max()
df['Sales'].min()

np.int64(100)

In [18]:
df['Sales'].agg(['min', 'max', 'sum', 'mean', 'count', 'std'])

min       100.000000
max       300.000000
sum      1500.000000
mean      187.500000
count       8.000000
std        66.062741
Name: Sales, dtype: float64

## Pivot Tables

In [20]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': [
        'East', 'West', 'North', 'South',
        'East', 'West', 'North', 'South',
        'East', 'West', 'North', 'South',
        'East', 'West', 'North', 'South',
        'East', 'West', 'North', 'South'
    ],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': [
        'John', 'Mary', 'Bob', 'Alice',
        'John', 'Mary', 'Bob', 'Alice',
        'John', 'Mary', 'Bob', 'Alice',
        'John', 'Mary', 'Bob', 'Alice',
        'John', 'Mary', 'Bob', 'Alice'
    ]
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    103     97   John  January      Q1
1  2023-01-02       B   West    163     50   Mary  January      Q1
2  2023-01-03       C  North    283     52    Bob  January      Q1
3  2023-01-04       D  South    975     55  Alice  January      Q1
4  2023-01-05       A   East    541     85   John  January      Q1
5  2023-01-06       B   West    974     78   Mary  January      Q1
6  2023-01-07       C  North    178     83    Bob  January      Q1
7  2023-01-08       D  South    708     93  Alice  January      Q1
8  2023-01-09       A   East    469     46   John  January      Q1
9  2023-01-10       B   West    416     62   Mary  January      Q1
10 2023-01-11       C  North    265     51    Bob  January      Q1
11 2023-01-12       D  South    166     24  Alice  January      Q1
12 2023-01-13       A   East    956     35   John  January      Q1
13 2023-01-14       B   West    809     94   Mary  January      Q1
14 2023-01-15       C  North    320     33    Bob  January      Q1
15 2023-01-16       D  South    195     47  Alice  January      Q1
16 2023-01-17       A   East    116     30   John  January      Q1
17 2023-01-18       B   West    233     23   Mary  January      Q1
18 2023-01-19       C  North    685     58    Bob  January      Q1
19 2023-01-20       D  South    951     95  Alice  January      Q1

In [22]:
pd.pivot_table(df, values= 'Sales', index= 'Region', columns='Product')

Product      A      B      C      D
Region
East     437.0    NaN    NaN    NaN
North      NaN    NaN  346.2    NaN
South      NaN    NaN    NaN  599.0
West       NaN  519.0    NaN    NaN

In [28]:
pivot = pd.pivot_table(df, values= ['Sales', 'Units'], index= 'Region', columns='Product')
pivot

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     437.0    NaN    NaN    NaN  58.6   NaN   NaN   NaN
North      NaN    NaN  346.2    NaN   NaN   NaN  55.4   NaN
South      NaN    NaN    NaN  599.0   NaN   NaN   NaN  62.8
West       NaN  519.0    NaN    NaN   NaN  61.4   NaN   NaN

In [30]:
# Crosstab
pd.crosstab(df['Region'], df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

## Operations

In [32]:
df1 = pd.DataFrame({
    'A': [1,2,3,4,5],
    'B': [10,20,30,40,50],
    'C': [100,200,300,400,500]
})
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [35]:
df1.shape

(5, 3)

In [37]:
df1.columns

Index(['A', 'B', 'C'], dtype='str')

In [39]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [42]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [45]:
df1['B'] + 10

0    20
1    30
2    40
3    50
4    60
Name: B, dtype: int64

In [47]:
def square(x):
    return x**2

In [48]:
df1['B'].apply(square)

0     100
1     400
2     900
3    1600
4    2500
Name: B, dtype: int64