In [12]:
import numpy as np
import pandas as pd

# Pandas Series

A series is a one dimentional labeled array capable of holding any data type. The axis lables are collectively called index

In [16]:
labels = ['a', 'b', 'c']
list = [10, 20, 30]
arr = np.array([10,20,30])
dict = {1:10, 2:20, 3:30}

In [21]:
pd.Series(list, index=labels)

a    10
b    20
c    30
dtype: int64

In [23]:
pd.Series(dict)

1    10
2    20
3    30
dtype: int64

# DataFrames
When You combine multiple series together then it's called as Dataframes

In [27]:
data = {
    'Name': ['Mac', 'Kam', 'Sak', 'Bo'],
    'Age': [21, 22, 20, 25],
    'City': ['In', 'In', 'Cam', 'Cam'],
    'Salary': [2000000, 30000, 40000, 50000]
}

df = pd.DataFrame(data)

In [30]:
df

  Name  Age City   Salary
0  Mac   21   In  2000000
1  Kam   22   In    30000
2  Sak   20  Cam    40000
3   Bo   25  Cam    50000

In [37]:
data_list = [
    ['Macc', 20, 'In', 20000000],
    ['Sak', 19, 'Cam', 3000000],
    ['Kam', 22, 'In', 900000],
    ['Bo', 25, 'Cam', 1000000]
]

df2 = pd.DataFrame(data_list)
columns = ["Name", "Age","City", "Salary"]
df2 = pd.DataFrame(data_list, columns=columns)
df2

   Name  Age City    Salary
0  Macc   20   In  20000000
1   Sak   19  Cam   3000000
2   Kam   22   In    900000
3    Bo   25  Cam   1000000

In [38]:
df2

   Name  Age City    Salary
0  Macc   20   In  20000000
1   Sak   19  Cam   3000000
2   Kam   22   In    900000
3    Bo   25  Cam   1000000